import Image from 'next/image';
import React from 'react';
import Link from 'next/link';
import Head from 'next/head';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
// import styles from '../../styles/Home.module.css';

// import 
export default function CarDetails() {
  return (
    <>
    <div className="container">
      <Head>
        <title>Car Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon_io.ico" />
      </Head>

      <main >
        <Header />
        <div className="main-container details-page">
        <div className="page-header">
          <div className="header-details-block">
            <Link href="/home" >
              <a>
              <div className="header-nav-back">
                <Image src="/images/back-arrow.svg" alt="back arrow" height={10.67} width={13.33} />
              </div>
              </a>
            </Link>
            <div className="header-details-box">
              <p className='page-title' >2022 Ford F-250 Super Duty</p>
              <span className='page-subtitle' >Covert Buick GMC  •  3,518 Mileage  •  Black</span>
              <span className='page-subtitle' >Austin, Texas</span>
            </div>
          </div>
          <div className="header-actions-block">
            <div className="car-price-box">
              <p className="font-[600] text-[28px] leading-[38px] text-[#28293D]" >$87,698</p>
              <Image src="/images/info.svg" height={16} width={16} alt='info' />
            </div>
            <button className='card-action-btn'>
              <span>Invite dealer</span>
              <Image src="/images/arrow.svg" alt="arrow" layout="fixed" width={15} height={24} />
            </button>
          </div>
        </div>
        </div>
        <div className="offer-block" >
          <div className="offer-block-container" >
            {/* <div className=""> */}
              <div className="flex items-center">
                <Image src="/images/green-star.svg" height="20px" width="15px" alt="Special Offers" />
                <p className="ml-[4px] text-[12px] font-[600] leading-[20px] text-[#05A660] uppercase">Special Offers</p>
              </div>
              <div className='flex items-center gap-[16px]'>
                <p className="flex items-center gap-[6px]">
                  <span className="h-[4px] w-[4px] rounded-[2px] bg-black mr-[4px] block"></span>
                  <span>100% credit approval guaranteed</span>
                </p>
                <p className="flex items-center gap-[6px]">
                <span className="h-[4px] w-[4px] rounded-[2px] bg-black mr-[4px] block"></span>
                <span>Complimentary 101pt safety check</span>
                </p>
              </div>
            {/* </div> */}
          </div>
        </div>
        <div className="car-slider-section"></div>
        <div className="car-details-section">
          <div className="car-details-container">
            <div className="car-details-container-title">
              <p>Car details</p>
            </div>          
            <div className="car-details-grid-box">
              <div className="car-details-box">
                <div className="car-details-icon-box">
                  {/* <Image src="/images/car.svg" layout='full' alt="car details" /> */}
                </div>
              </div>
            </div>          
          </div>
          <div className="car-details-container">
            <div className="car-details-container-title">
              <p>Other features</p>
            </div>          
          </div>
        </div>
        <Footer />
      </main>

    </div>
    </>
  )
}
