import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Main from '../components/Main';
// import Router from "next/router";
// import { useSelector } from 'react-redux';

export default function Home() {
  // const cars = useSelector(state => state.cars);
  // console.log(cars.data.length);
  // if(!cars.data.length > 0){
  //   Router.push("/");
  // }
return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon_io.ico" />
      </Head>
      <main>
        <Header />
        <Main/>
        <Footer />
      </main>
    </div>
  )
}
