import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Main from '../components/Main';
import { wrapper } from '../app/store';
import { getData } from './api/data';
import { setAll } from '../reducers/carsSlice';

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon_io.ico" />
      </Head>
      <main>
        <Header />
        <Main/>
        <Footer />
      </main>
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    const jsonData = await getData();
    store.dispatch(setAll(jsonData));
  }
);
